name: Python application

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ${{ github.workspace }}/backend  # Set PYTHONPATH globally for the job

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install flake8 pytest schemathesis requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        cd backend
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Start Flask app
      run: |
        cd backend
        nohup python app.py &
        for i in {1..10}; do
          if curl -s http://127.0.0.1:5000/; then
            echo "Flask app is up!"
            break
          fi
          echo "Waiting for Flask app to start..."
          sleep 5
        done

    - name: Test with pytest
      run: |
        cd backend
        pytest
